image: gitlab.chab.ethz.ch:4567/reiher/docker/qcmaquis-gcc:latest

# Pipeline that compiles the code with increasingly complex models

stages:
  - buildBasic
  - testBasic  
  - buildAdvanced
  - testAdvanced
  - buildFinal
  - testFinal

# Conventional electronic-structure tests

build-electronic:
  stage: buildBasic
  tags:
    - default_docker
  script:
    - mkdir buildElectronic && cd buildElectronic
    - cmake -DQCMAQUIS_TESTS=ON -DBUILD_SYMMETRIES="TwoU1;TwoU1PG;SU2U1;SU2U1PG" -DCMAKE_BUILD_TYPE=Release -DBUILD_DMRG_FEAST=ON -DBUILD_SRCAS=ON ../dmrg
    - make -j2
  artifacts:
    paths:
      - buildElectronic/
    expire_in: 6h
    when: always

testElectronic:
  stage: testBasic
  needs: ["build-electronic"]
  tags:
    - default_docker
  script:
    - cd buildElectronic
    - make CTEST_OUTPUT_ON_FAILURE=1 test

# Relativistic electronic-structure tests

build-relativistic:
  stage: buildAdvanced
  needs: ["testElectronic"]
  tags:
    - default_docker
  script:
    - mkdir buildRelativistic && cd buildRelativistic
    - cmake -DQCMAQUIS_TESTS=ON -DBUILD_SYMMETRIES="TwoU1;TwoU1PG;SU2U1;SU2U1PG;U1DG" -DCMAKE_BUILD_TYPE=Release ../dmrg
    - make -j2
  artifacts:
    paths:
      - buildRelativistic/
    expire_in: 6h
    when: always

testRelativistic:
  stage: testAdvanced
  needs: ["build-relativistic"]
  tags:
    - default_docker
  script:
    - cd buildRelativistic
    - make CTEST_OUTPUT_ON_FAILURE=1 test

# Non-electronic-structure tests

buildPreBO:
  stage: buildFinal
  needs: ["testRelativistic"]
  tags:
    - default_docker
  script:
    - mkdir buildNU1 && cd buildNU1
    - cmake -DQCMAQUIS_TESTS=ON -DBUILD_SYMMETRIES="TwoU1;TwoU1PG;SU2U1;SU2U1PG;U1DG;NU1" -DCMAKE_BUILD_TYPE=Release -DBUILD_PREBO=ON -DDMRG_NUMSYMM=5  ../dmrg
    - make -j2
  artifacts:
    paths:
      - buildNU1/
    expire_in: 6h
    when: always

testPreBO:
  stage: testFinal
  needs: ["buildPreBO"]
  tags:
    - default_docker
  script:
    - cd buildNU1
    - make CTEST_OUTPUT_ON_FAILURE=1 test

buildVibrationalHamiltonians:
  stage: buildFinal
  needs: ["testRelativistic"]
  tags:
    - default_docker
  script:
    - mkdir buildVibrational && cd buildVibrational
    - cmake -DQCMAQUIS_TESTS=ON -DBUILD_SYMMETRIES="NONE" -DCMAKE_BUILD_TYPE=Release -DBUILD_VIBRATIONAL=ON -DBUILD_DMRG_FEAST=ON -DBUILD_SRCAS=ON -DBUILD_MPS2CI=ON -DDMRG_ORDERNONE=12 ../dmrg
    - make -j2
  artifacts:
    paths:
      - buildVibrational/
    expire_in: 6h
    when: always

testVibrationalHamiltonians:
  stage: testFinal
  needs: ["buildVibrationalHamiltonians"]
  tags:
    - default_docker
  script:
    - cd buildVibrational
    - make CTEST_OUTPUT_ON_FAILURE=1 test

buildVibronicHamiltonians:
  stage: buildFinal
  needs: ["testRelativistic"]
  tags:
    - default_docker
  script:
    - mkdir buildVibronic && cd buildVibronic
    - cmake -DQCMAQUIS_TESTS=ON -DBUILD_SYMMETRIES="TwoU1PG;SU2U1PG;NU1;U1" -DCMAKE_BUILD_TYPE=Release -DBUILD_VIBRONIC=ON ../dmrg
    - make -j2
  artifacts:
    paths:
      - buildVibronic/
    expire_in: 6h
    when: always

testVibronicHamiltonians:
  stage: testFinal
  needs: ["buildVibronicHamiltonians"]
  tags:
    - default_docker
  script:
    - cd buildVibronic
    - make CTEST_OUTPUT_ON_FAILURE=1 test

# +-----------------------------+
#  Pipeline for the TD-DMRG case
# +-----------------------------+

# Tests TD-DMRG with Electronic Hamiltonians

build-TD-conventional:
  stage: buildBasic
  tags:
    - default_docker
  script:
    - mkdir buildTDConventional && cd buildTDConventional
    - cmake -DQCMAQUIS_TESTS=ON -DBUILD_SYMMETRIES="TwoU1;TwoU1PG;SU2U1;SU2U1PG" -DCMAKE_BUILD_TYPE=Release -DBUILD_DMRG_EVOLVE=ON ../dmrg
    - make -j2
  artifacts:
    paths:
      - buildTDConventional/
    expire_in: 6h
    when: always

testTDConventional:
  stage: testBasic
  needs: ["build-TD-conventional"]
  tags:
    - default_docker
  script:
    - cd buildTDConventional
    - make CTEST_OUTPUT_ON_FAILURE=1 test

# Tests TD-DMRG with all Hamiltonians

build-TD-with-all-symmetries:
  stage: buildAdvanced
  needs: ["testTDConventional"]
  tags:
    - default_docker
  script:
    - mkdir buildTDAllSymmetries && cd buildTDAllSymmetries
    - cmake -DQCMAQUIS_TESTS=ON -DBUILD_SYMMETRIES="TwoU1;TwoU1PG;SU2U1;SU2U1PG;U1DG;NU1;U1" -DCMAKE_BUILD_TYPE=Release -DBUILD_DMRG_EVOLVE=ON -DBUILD_PREBO=ON -DBUILD_VIBRONIC=ON ../dmrg
    - make -j2
  artifacts:
    paths:
      - buildTDAllSymmetries/
    expire_in: 6h
    when: always

testTDAllSymmetries:
  stage: testAdvanced
  needs: ["build-TD-with-all-symmetries"]
  tags:
    - default_docker
  script:
    - cd buildTDAllSymmetries
    - make CTEST_OUTPUT_ON_FAILURE=1 test
